# Site settings
title: VROCK
description: "A Jekyll theme for developers"
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br



# User settings
username: VROCK
user_description: "Hi, folks and welcome to my blog. I'm a passionated senior system engineer who's always open for learning new things. So check out my work."
user_title: by Tobias Geiser
twitter_username: public_vrock
github_username:  public-vrock
repository_name: public-vrock.github.io

# Algolia search settings
algolia:
  application_id: 'your_application_id'
  index_name: 'your_index_name'
  search_only_api_key: 'your_search_only_api_key'
  powered_by: true

# Google-analytics
google-analytics:
  id: ""

exclude: ['src' , 'node_modules']

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

#plugins:
#  - jekyll-minifier


# Github settings
repository: public-vrock/public-vrock.github.io
github: [metadata]