name: Build Jekyll theme

on:
  pull_request:
  push:
    branches:
      - master
      - feat/refresh-modern

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build
        run: bundle exec jekyll build
